<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DigiFikileLms.API</AssemblyName>
    <RootNamespace>DigiFikileLms.API</RootNamespace>
    <rollForward>LatestMajor</rollForward> 
    
     
    <UserSecretsId>a7eaf0e2-2fb7-43d1-8262-8f1ef67fb35a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DigiFikileLms.Application\DigiFikileLms.Application.csproj" />
    <ProjectReference Include="..\DigiFikileLms.Infrastructure\DigiFikileLms.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.18.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.22" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
